using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PFMP_API.Models
{
    /// <summary>
    /// Daily market context digest generated by AI from financial news
    /// Provides market awareness for AI advisors
    /// </summary>
    public class MarketContext
    {
        [Key]
        public int MarketContextId { get; set; }

        [Required]
        public DateTime ContextDate { get; set; }

        /// <summary>
        /// AI-generated summary of the day's financial news and market movements
        /// </summary>
        [Required]
        [MaxLength(2000)]
        public string DailySummary { get; set; } = string.Empty;

        /// <summary>
        /// Overall market sentiment: Bullish, Bearish, Neutral, Volatile
        /// </summary>
        [Required]
        [MaxLength(20)]
        public string MarketSentiment { get; set; } = "Neutral";

        /// <summary>
        /// Major events that day (JSON array): ["Fed rate hike", "Inflation data", "Tech earnings"]
        /// </summary>
        [Column(TypeName = "jsonb")]
        public List<string> MajorEvents { get; set; } = new();

        /// <summary>
        /// Sectors significantly affected (JSON array): ["Technology", "Energy", "Healthcare"]
        /// </summary>
        [Column(TypeName = "jsonb")]
        public List<string> AffectedSectors { get; set; } = new();

        /// <summary>
        /// S&P 500 (SPY) percentage change for the day
        /// </summary>
        [Column(TypeName = "decimal(8,4)")]
        public decimal SPYChange { get; set; }

        /// <summary>
        /// VIX (volatility index) closing level
        /// </summary>
        [Column(TypeName = "decimal(8,2)")]
        public decimal VIXLevel { get; set; }

        /// <summary>
        /// Crypto market sentiment (optional): Bullish, Bearish, Neutral
        /// </summary>
        [MaxLength(20)]
        public string? CryptoSentiment { get; set; }

        /// <summary>
        /// 10-year Treasury yield (as percentage)
        /// </summary>
        [MaxLength(10)]
        public string? TreasuryYield10Y { get; set; }

        /// <summary>
        /// When this context was generated
        /// </summary>
        [Required]
        public DateTime GeneratedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Total tokens used to generate this summary
        /// </summary>
        public int TokensUsed { get; set; }

        /// <summary>
        /// Cost to generate this summary (USD)
        /// </summary>
        [Column(TypeName = "decimal(10,6)")]
        public decimal GenerationCost { get; set; }

        /// <summary>
        /// Source article count used for summary
        /// </summary>
        public int SourceArticleCount { get; set; }

        /// <summary>
        /// Model used for summarization (e.g., "gemini-1.5-pro")
        /// </summary>
        [MaxLength(50)]
        public string? ModelUsed { get; set; }
    }
}
